apiVersion: v1
kind: Service
metadata:
  name: serv-user
  labels:
    app: serv-user
spec:
  selector:
    app: serv-user
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: ClusterIP
