name: ChatService CI

on:
  push:
    paths:
      - 'ChatService/**'
  pull_request:
    paths:
      - 'ChatService/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        working-directory: ChatService
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        working-directory: ChatService
        env:
          PYTHONPATH: "./"
        run: pytest tests/

  build_and_push:
    runs-on: ubuntu-latest
    needs: test  # test job이 성공적으로 완료된 후 실행

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: ~/.cache/docker
          key: ${{ runner.os }}-build-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-build-

      - name: Build Docker image for Chat Service
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/example:serv_chat ./ChatService
          
      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/example:serv_chat